packages:
  - apps/*
  - packages/*
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  sharp: true
  unrs-resolver: true
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
